"""empty message

Revision ID: 32459e6c9658
Revises: 7a8fab1986e1
Create Date: 2022-01-22 18:38:13.813928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32459e6c9658'
down_revision = '7a8fab1986e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invDispositivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=45), nullable=True),
    sa.Column('producto', sa.String(length=45), nullable=True),
    sa.Column('marca', sa.String(length=45), nullable=True),
    sa.Column('modelo', sa.String(length=45), nullable=True),
    sa.Column('origen', sa.String(length=45), nullable=True),
    sa.Column('foto', sa.Text(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.Column('lugarId', sa.Integer(), nullable=False),
    sa.Column('pertenece', sa.String(length=45), nullable=True),
    sa.Column('descompostura', sa.String(length=100), nullable=True),
    sa.Column('costo', sa.Integer(), nullable=True),
    sa.Column('compra', sa.String(length=100), nullable=True),
    sa.Column('proveedor', sa.String(length=100), nullable=True),
    sa.Column('idMov', sa.Text(), nullable=True),
    sa.Column('fechaAlta', sa.DateTime(), nullable=True),
    sa.Column('fechaUltimaModificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lugarId'], ['invLugares.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invDispositivos')
    # ### end Alembic commands ###
