"""empty message

Revision ID: 955bbff04a94
Revises: b282b7715e0b
Create Date: 2022-03-22 00:31:11.869969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955bbff04a94'
down_revision = 'b282b7715e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invDispositivos', sa.Column('serie', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invDispositivos', 'serie')
    # ### end Alembic commands ###
