"""empty message

Revision ID: b282b7715e0b
Revises: f027b083cb5a
Create Date: 2022-02-22 23:42:32.819229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b282b7715e0b'
down_revision = 'f027b083cb5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invDispositivos', sa.Column('statusId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'invDispositivos', 'invStatusDevices', ['statusId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invDispositivos', type_='foreignkey')
    op.drop_column('invDispositivos', 'statusId')
    # ### end Alembic commands ###
