"""empty message

Revision ID: ca4886a3b8d5
Revises: 955bbff04a94
Create Date: 2022-04-20 11:43:01.394819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4886a3b8d5'
down_revision = '955bbff04a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invDispositivos', sa.Column('accesorios', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invDispositivos', 'accesorios')
    # ### end Alembic commands ###
